fix a typo in the field sweep
jmfrancklab/FLinst pull request #15
Opened 2024-08-07 21:40 UTC by wfkincaid

2024-08-08 12:00 UTC, jmfranck requested changes

2024-08-08 12:00 UTC, jmfranck commented on examples/run_field_dep_justMw.py
> +sweep_data.set_prop("postproc_type", "proc_field_sweep_v2")
The dictionary key is not called this. That's the function name

2024-08-08 12:00 UTC, jmfranck commented on examples/run_field_dep_justMw.py
> +#    )
Don't commit commented out code. But, I do think this is a good chance to remove the processing from the acquisition code

2024-08-08 12:00 UTC, jmfranck commented on examples/run_field_dep_justMw.py
> +    sweep_data.reorder(["ph1", "indirect", "nScans", "t2"])
Just do: 
```
sweep_data.reorder(['ph1']).reorder(['t2'], first=False) 
```

2024-08-09 12:59 UTC, jmfranck requested changes
- There should be no forplot object created, since you're not plotting.
- there are multiple nested blocks that all about nScans at the end... That also should not be needed
- just use the new function to save the date at the end

2024-08-09 13:01 UTC, jmfranck commented on examples/run_field_dep_justMw.py
> -    sweep_data.squeeze()
Don't remove this

2024-08-09 17:10 UTC, wfkincaid commented on examples/run_field_dep_justMw.py
> -    sweep_data.squeeze()
Are you suggesting I keep both what was here and the modified function suggested yesterday?

2024-08-09 17:45 UTC, jmfranck commented on examples/run_field_dep_justMw.py
> -    sweep_data.squeeze()
sorry -- no.  Leave the squeeze, not the `reorder` on the line before.  That was unclear.

2024-08-09 17:46 UTC, jmfranck commented on examples/run_field_dep_justMw.py
> +sweep_data.squeeze()
here you're doing what I'm asking w.r.t. [this conversation](https://github.com/jmfrancklab/FLinst/pull/15/files#r1711826303), which is resolved.

2024-08-09 17:47 UTC, jmfranck commented on examples/run_field_dep_justMw.py
> +    sweep_data.setaxis("nScans", r_[0 : config_dict["nScans"]])
there's a shortcut for what you're doing here, which is `sweep_data.setaxis('nScans','#')`

2024-08-09 17:48 UTC, jmfranck commented on examples/run_field_dep_justMw.py
> +saving_field = save_data(sweep_data, target_directory, config_dict, "field")
yes, great

2024-08-09 17:49 UTC, jmfranck commented on examples/run_field_dep_justMw.py
>  nodename = sweep_data.name()
this line is not used/needed -- probably trips flake, but remove in either case

2024-08-09 17:50 UTC, jmfranck commented on examples/run_field_dep_justMw.py
>  filename_out = filename + ".h5"
this line is also unused /deleted, as well as the code used to generate `filename`

2024-08-09 17:51 UTC, jmfranck commented on examples/run_field_dep_justMw.py
> +
do not FT before saving -- we don't do that.

2024-08-09 17:51 UTC, jmfranck commented on examples/run_field_dep_justMw.py
>  sweep_data.set_prop("postproc_type", "field_sweep_v2")
change this to v3 -- I think that there are several things that have changed

2024-08-09 17:52 UTC, jmfranck commented on examples/run_field_dep_justMw.py
> +
(this is just a standard -- we chunk the data so that it's properly organized, but don't manipulate the numbers inside the data in any way)

2024-08-09 19:31 UTC, wfkincaid commented on examples/run_field_dep_justMw.py
> +saving_field = h5py.save_data(sweep_data, target_directory, config_dict, "field")
Should I define this from pyspecdata or h5py, is this okay?

2024-08-09 21:02 UTC, jmfranck approved these changes

2024-08-09 21:02 UTC, jmfranck commented on examples/run_field_dep_justMw.py
> +import h5py as h5py
Just don't make this change

2024-08-09 21:02 UTC, jmfranck commented on examples/run_field_dep_justMw.py
> +myinput = input(psd.strm("Your field axis is:", field_axis, "\nDoes this look okay?"))
Don't make this or following change

2024-08-09 21:07 UTC, merged