ppg to capture a single pulse on GDS scope
jmfrancklab/FLinst pull request #16
Opened 2024-08-13 18:00 UTC by guinneak198

script for very rough straightforward acquisition of a single pulse on the GDS scope

2024-08-13 18:51 UTC, jmfranck commented on examples/simple_onepulse_capture.py
> +data.set_prop("acq_params", config_dict.asdict())
Set postproc type

2024-08-15 19:55 UTC, jmfranck commented
[this PR](https://github.com/jmfrancklab/FLinst/pull/3) must be resolved first

2024-08-21 15:40 UTC, jmfranck commented
please see comments in code `# PR`

2024-08-21 17:07 UTC, guinneak198 commented
I was under the impression we wanted this script as bare bones as possible and so had taken out the functions you mentioned giving the user control of the timescale etc without messing with function parameters. but added back in

2024-08-25 00:00 UTC, jmfranck requested changes
just one thing, and then we should be able to merge.
Thanks for getting this to such a good state!

2024-08-25 00:00 UTC, jmfranck commented on examples/simple_onepulse_capture.py
> +    thiscapture = thiscapture["t":(0, None)]["t":(None, 24e6)]
why isn't this just `["t":(0,24e6)]`?  If there is a reason, can you add a comment?

2024-08-26 15:09 UTC, guinneak198 commented on examples/simple_onepulse_capture.py
> +    thiscapture = thiscapture["t":(0, None)]["t":(None, 24e6)]
was basing off of other acquisition scriptss but adjusted to (0,24e6) - I agree this way is more straightforward

2024-08-26 16:09 UTC, merged